export const enUs: Record<string, string> = {
	Title: "En Visualizer",
	"Dice.Advantage": "Advantage",
	"Dice.Boost": "Boost",
	"Dice.Despair": "Despair",
	"Dice.Failure": "Failure",
	"Dice.Setback": "Setback",
	"Dice.Success": "Success",
	"Dice.Threat": "Threat",
	"Dice.Triumph": "Triumph",
	Search: "Search",
	Distribution: "Distribution of {a}",
	"Distribution.And": " and {b}",
	ProbabilityHeader: "Probability Breakdown",
	Symbols: "Symbols and Calculations",
	"Symbols.Mode": "{a} Symbols",
	"Symbols.Calculation": "Calculation",
	Breakdowns: "Probability Breakdowns",
	"Breakdowns.Total": "Total Frequency",
	"Breakdowns.Frequency": "{a} Frequency",
	"Breakdowns.Probability": "Probability of {a}",
	"Breakdowns.Average": "Average {a}",
	"Breakdowns.StandardDeviation": "Standard Deviation",
	Advanced: "Advanced",
	"Advanced.Probability": "Probability",
	"Advanced.Compare": "Compare to",
	"Advanced.And": "and",
	DataTable: "Data Table",
	"DataTable.Net": "Net {a}",
	"DataTable.Frequency": "Frequency",
	"DataTable.Total": "Total {a}",
};
