export const jp: Record<string, string> = {
	Title: "Visualizer",
	Language: "語",
	"Dice.Advantage": "利点",
	"Dice.Boost": "高める",
	"Dice.Despair": "絶望",
	"Dice.Failure": "失敗",
	"Dice.Setback": "挫折",
	"Dice.Success": "成功",
	"Dice.Threat": "脅威",
	"Dice.Triumph": "勝利",
	Search: "探す",
	Distribution: "{a}の配布",
	"Distribution.And": "と{b}",
	ProbabilityHeader: "確率の内訳",
	Symbols: "記号と計算",
	"Symbols.Mode": "{a}記号",
	"Symbols.Calculation": "計算",
	Breakdowns: "確率の内訳",
	"Breakdowns.Total": "総頻度",
	"Breakdowns.Frequency": "{a}周波数",
	"Breakdowns.Probability": "{a}の確率",
	"Breakdowns.Average": "平均{a}",
	"Breakdowns.StandardDeviation": "標準偏差",
	Advanced: "高度な",
	"Advanced.Probability": "確率",
	"Advanced.Compare": "Compare to",
	"Advanced.And": "と",
	DataTable: "データ表",
	"DataTable.Net": "ネット {a}",
	"DataTable.Frequency": "周波数",
	"DataTable.Total": "合計{a}",
	BadRequest: "クエリに対してデータが返されませんでした",
};
