export const mi: Record<string, string> = {
	Title: "Visualizer",
	Language: "Reo",
	"Dice.Advantage": "Painga",
	"Dice.Boost": "Whakarei",
	"Dice.Despair": "Hepohepo",
	"Dice.Failure": "Rahua",
	"Dice.Setback": "Mahinga Whakamuri",
	"Dice.Success": "Angitu",
	"Dice.Threat": "Fakamanamana",
	"Dice.Triumph": "Wikitoria",
	Search: "Rapu",
	Distribution: "Tohatoha o {a}",
	"Distribution.And": " me {b}",
	ProbabilityHeader: "Pakaruhanga Puku",
	Symbols: "Tohu me te Tatau",
	"Symbols.Mode": "{a} Tohu",
	"Symbols.Calculation": "Tatau",
	Breakdowns: "Nga Papahinga Puku",
	"Breakdowns.Total": "Mahinga Katoa",
	"Breakdowns.Frequency": "{a} Auautanga",
	"Breakdowns.Probability": "Te tupono o {a}",
	"Breakdowns.Average": "Wawaenga {a}",
	"Breakdowns.StandardDeviation": "Wehenga Paerewa",
	Advanced: "Arā Atu Anō",
	"Advanced.Probability": "Mahinga",
	"Advanced.Compare": "TR Compare to",
	"Advanced.And": "me",
	DataTable: "Papa Ripanga",
	"DataTable.Net": "{a} Kupenga",
	"DataTable.Frequency": "Auautanga",
	"DataTable.Total": "{a} Katoa",
};
